#!/usr/bin/env python3
import argparse, json
from pathlib import Path
root=Path(__file__).resolve().parents[1]
p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');args=p.parse_args()
catalog=json.loads((root/'data/ui-locales.json').read_text())
assert all(key.count('{n}') == value[locale].count('{n}') for key,value in catalog.items() for locale in ['kk','en']), 'Placeholder count mismatch'
assert all(set(value)=={'kk','en'} and all(value.values()) for value in catalog.values())
expected='/* Generated by scripts/build_ui_locales.py from authored UI copy. */\nglobalThis.DisarmLocaleCatalog = '+json.dumps(catalog,ensure_ascii=False,sort_keys=True,indent=2)+';\n'
path=root/'assets/ui-locales.js'
if args.check:
 assert path.read_text()==expected,'Stale locale asset'
else:path.write_text(expected)
print(f'UI locale catalog: {len(catalog)} RU/KK/EN entries')
